### PR TITLE
fix: change TextProps from type to interface to enable declaration me…

### PR DESCRIPTION
**Pull request by wkoutre**
…rging

**What kind of change does this PR introduce?**

Please see my comment [here](https://github.com/react-native-elements/react-native-elements/issues/2310#issuecomment-916561196) and the [follow up](https://github.com/react-native-elements/react-native-elements/issues/2310#issuecomment-916908717).

This is a Typescript-related bug fix.

**Did you add tests for your changes?**

No.

**If relevant, did you update the documentation?**

Yes!

**Summary**

Please refer to links above.

**Does this PR introduce a breaking change?**

Not as far as I can tell in my review of where `TextProps` is used.

### CODE REVIEW

**Comment by wkoutre** [comment]
Hi, any word on this?

**Comment by mdjarv** [comment]
I ran into this issue when trying to follow the documentation to augment `TextProp` with a few more styles.

Until this is merged the documentation below is incorrect
https://reactnativeelements.com/docs/customization#typescript-definitions-extending-the-default-theme

**Comment by arpitBhalla** [comment]
Could you please resolve conflict.

**Comment by wkoutre** [comment]
@arpitBhalla All set.

**Comment by arpitBhalla** [comment]
Don't we need to change types to interface for all components?

**Comment by wkoutre** [comment]
Doing so would enable declaration merging for everything, yes. Would you like me to do so in this PR? I could otherwise submit another with these broader changes, whichever is preferred.

**Comment by arpitBhalla** [comment]
For sure you can do it in another PR

**Pull request merged**
