### PR TITLE
fix CheckBox right prop not working

### LINKED ISSUE #2848: CheckBox: right prop is not working
Current behavior:
* setting `right` to `true` does nothing

Expected behavior:
* setting `right` to `true` must move the icon to the right (as mentioned in the docs https://reactnativeelements.com/docs/checkbox#right)

### PR DESCRIPTION
**Pull request by ankushdutt**
fixes #2848

### CODE REVIEW

**Comment by flyingcircle** [comment]
Both the props `right` and `center` seem kind of pointless. How about we just remove them instead?

**Comment by ankushdutt** [comment]
Sure! Removing

**Comment by ankushdutt** [comment]
updated @flyingcircle!

**Comment by ankushdutt** [comment]
Hey @flyingcircle, looks like the `right` and `center` props are for aligning the checkbox along with the text horizontally. They seem to be working fine when container width is large enough.
See Screenshot:
image
image

I'll go ahead and close this one.

**Pull request closed without merging**
