### PR TITLE
[Add] Reddit social icon

### PR DESCRIPTION
**Pull request by sanand34**
**What kind of change does this PR introduce?**  refactoring

**Did you add tests for your changes?**  No

**If relevant, did you update the documentation?**  No

**Summary**
Tested this on react native elements expo app by changing this package in the node modules

**Does this PR introduce a breaking change?**  No

**Other information**

### CODE REVIEW

**Comment by flyingcircle** [comment]
Please clean up code.

**Comment by sanand34** [comment]
I cleaned up the code.

**Comment by sanand34** [comment]
> Please clean up code.
I cleaned up the code

**Comment by flyingcircle** [comment]
The `prettier` check is still failing. There's a prettify command that you should be able to run to test that out locally.

**Comment by flyingcircle** [comment]
It could also just be that you need to merge in the latest `next` branch.

**Comment by sanand34** [comment]
Used prettier locally in my machine to prettify the code ,now it should be okay I guess.

**Comment by sanand34** [comment]
Screen Shot 2021-08-10 at 9 22 56 AM
Screen Shot 2021-08-10 at 9 24 37 AM

**Comment by sanand34** [comment]
Ran both prettify and test commands locally now after cleaning up the code again.

**Pull request merged**
