### PR TITLE
[ThemeProvider] Class to FC & Performance improved

### LINKED ISSUE #3026: themeKey prop from withTheme should be optional or default to ''
**Explain what you did (Required)**

Upgrade to react-native-elements 3.4.1

**Expected behavior (Required)**

The withTheme function should not have typescript errors and should not impose a themekey prop. Not all custom components need a key and they just need to inject the theme object and it seems that the Themed component handles an undefined themeKey

**Describe the bug (Required)** 
image

**To Reproduce (Required)**

upgrade from version 3.0.0 to 3.4.1

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |     3.4.1    |
| react-native          |      0.64.1   |

### LINKED ISSUE #3034: Override colors
I want to change the default theme. And everything works fine, except for the color. The color does not change

```js
theme.js

export default themeBase = {
  colors: {
    primary: 'red'
  },
}

export const themeLight = {
  colors: {
    ...themeBase.colors,
    primary: 'green'
  }
  ...
}
```

```js
index.js

<ThemeProvider theme={themeBase}>
  <App />
</ThemeProvider>
```

```js
App.js

this.props.replaceTheme( themeLight )
// I expect to receive this.props.theme.colors.primary == 'green'
```

There is a function in the component `ThemeProvider`
```diff
.../node_modules/react-native-elements/dist/config/ThemeProvider.js:33

    static getDerivedStateFromProps(props, state) {
        const { useDark } = props;
        const isTheme = (theme) => {
            return !(Object.keys(theme).length === 0 && theme.constructor === Object);
        };
        //isTheme will check if the theme is provided by user and will update the theme only if its provided by user
        //Not checking if the theme exist or not will always result in if statement getting executed as props.theme !== state.theme if theme is not provided
        if (useDark !== state.useDark ||
            (isTheme(props.theme) && props.theme !== state.theme)) {
            const defaultColors = useDark ? darkColors : colors;
+          return {
+               theme: deepmerge(deepmerge({
+                   colors: defaultColors,
+               }, props.theme), state.theme),
+               useDark,
+          };
-           return {
-               theme: deepmerge(state.theme, deepmerge({
-                   colors: defaultColors,
-               }, props.theme)),
-               useDark,
-           };
        }
        return null;
    }
```
If you make the specified changes to it, then everything starts working.

What am I doing wrong?

react-native-elements: v3.4.1

npmPackages:
@react-native-community/cli: Not Found
react: 16.13.1 => 16.13.1
react-native: 0.63.4 => 0.63.4

### LINKED ISSUE #3037: [Theme] updateTheme doesn't switching colors on the fly/dynamically (Expo)
**Explain what you did (Required)**
Hi. We are using RNE and we are trying to change theme on the fly. We are using hook `useTheme` and method `updateTheme` to switch colors. I've attached repo with example

**Expected behavior (Required)**
We want have ability to switch Theme dynamically. We can do it now with local state of the main parent component and then pass it through all child component

Parent:
```
const [theme, setTheme] = useState(initialTheme)

if (...) { setTheme(theme2) } else { ... }

<ThemeProvider theme={theme}>
  {this.props.children}
</ThemeProvider>
```
Child:
```
const { theme } = useTheme()

<View style={{ color: theme.colors.primary }} />
```

Do you have any ideas how we can use `updateTheme`?

**Describe the bug (Required)**
We can't change theme colors on the fly with `updateTheme` method usage

**To Reproduce (Required)**
Repo - https://github.com/DenysMoro/rne-updateTheme-runtime
Release channel - https://expo.io/@taranis/projects/rne-updateTheme-runtime?release-channel=rne-updatetheme-runtime

**Screenshots (Required)**

https://user-images.githubusercontent.com/77282657/118392398-42381300-b642-11eb-8bdc-02c9c6c868a6.mov

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |   3.4.1      |
| react-native          |    0.63.2     |

### LINKED ISSUE #3088: Can't updateTheme
Hi team,
I have an issue when call updateTheme.  You can check this problem on below.

```
import * as React from 'react';
import { View, StyleSheet } from 'react-native';
import { Button, withTheme, ThemeProvider } from 'react-native-elements';

const theme = {
  colors: {
    primary: 'yellow',
  },
};

const AppText = withTheme(({ updateTheme }) => {
  return (
    <View style={styles.container}>
      <Button
        title="Hey"
        onPress={() =>
          updateTheme({
            colors: {
              primary: 'pink',
            },
          })
        }
      />
    </View>
  )
});

export default () => (
  <ThemeProvider theme={theme}>
    <AppText />
  </ThemeProvider>
);

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    paddingTop: 10,
    backgroundColor: '#ecf0f1',
    padding: 8,
  },
});

```
I checked and found issue line 61 to 69 in (https://github.com/react-native-elements/react-native-elements/blob/4f90e00919f4897a9a1320f74c8203ba7ec9e9f2/src/config/ThemeProvider.tsx)

I resloved issue with code on below. Can you update it ?
`
 static getDerivedStateFromProps(props, state) {
    const { useDark } = props;
    if (useDark !== state.useDark) {
      const defaultColors = useDark ? darkColors : colors;
      return {
        theme: deepmerge(
          deepmerge(
            {
              colors: defaultColors,
            },
            props.theme
          ),
          state.theme
        ),
        useDark,
      };
    }
    return null;
  }
`

Thanks,
Please help me!

### PR DESCRIPTION
**Pull request by arpitBhalla**
Preview https://snack.expo.io/@arpitbhalla/rne-latest-theme
- [ ] Closes #3026 
- [ ] Closes #3037
- [ ] Closes #3034 
- [ ] Closes #3088

### CODE REVIEW

**Comment by arpitBhalla** [comment]
@khushal87 Can you please verify this PR will fix those issues?

**Comment by arpitBhalla** [comment]
> Sure, I will review it and let you know. But can you explain how does it solve #3034?

No

**Comment by khushal87** [comment]
I will review and let you know @arpitBhalla

**Comment by arpitBhalla** [comment]
Hey @DenysMoro Can you confirm this PR works

**Review by khushal87 — COMMENTED** [review]
Hey @arpitBhalla. I went through the PR and I feel #3026 will be solved with this change. I am not sure how this is going to impact the other 2 issues which you mentioned. Can you explain?

**Comment by arpitBhalla** [comment]
Bhai feel na le, chala ke dekh

**Comment by arpitBhalla** [comment]
>  I am not sure how this is going to impact the other 2 issues which you mentioned
What I need to explain, the code itself tells what it is doing

**Comment by arpitBhalla** [comment]
@khushal87 

IMG_20210522_144310

**Comment by arpitBhalla** [comment]
@pranshuchittora @dhruvdutt @flyingcircle help needed

**Comment by pranshuchittora** [comment]
> @pranshuchittora @dhruvdutt @flyingcircle help needed

Yup. Tell us how can we help you.
P.S> I tried running the changes locally but not able to start the app 🤔

**Comment by arpitBhalla** [comment]
> > @pranshuchittora @dhruvdutt @flyingcircle help needed
> 
> Yup. Tell us how can we help you.
> P.S> I tried running the changes locally but not able to start the app

useEffect is causing the issue, 

```javascript 
 const coloredTheme=deepmerge(
      {
        colors: defaultColors,
      },
      theme
    );
const isThemeEqual=(isEqual(themeState, coloredTheme ))&&(JSON.stringify(themeState)===JSON.stringify(coloredTheme))

if(isThemeEqual){
...
   
```

**Pull request closed without merging**
