### PR TITLE
Few fixes and Improvements for Button

### PR DESCRIPTION
**Pull request by iRoachie**
Some nice improvements for button, mainly on android. Other non-visible changes are improvements to accessibility and a ripple fix for border-radius

### Ripple Color
The Ripple color now correctly matches the background and foreground text like it should.

**Solid (current)**
solid-current

**Solid (after)**
solid-after

**Clear (current)**
clear-current

**Clear (after)** 
clear-after

### CODE REVIEW

**Comment by Monte9** [comment]
Solid! Thanks for continually improving the library and making the elements even more polished! 💯 
Something I was curious about is measuring impact of changes like this? Button is one of the most commonly used RNE component.

Is there a way for us to track how many installs we have on the lastest version & what components are being used in the apps? Knowing the usage of each component will also help us prioritize work in the future.

**Comment by iRoachie** [comment]
Only thing I can think of is the used by statistic from github Screenshot 2019-10-15 at 3 32 26 PM

https://github.com/react-native-elements/react-native-elements/network/dependents

**Comment by iRoachie** [comment]
Also the changes can be undone if the user wants to preserve the old behaviour. The release notes for 2.0.0, outline breaking changes as well as what to change if a user wants to revert that behaviour

**Comment by Monte9** [comment]
Yeah, that github "used by" def gives us a based metric. Was wondering if there could be a Google Analytics like tool that sends metrics back each time a user import Button from RNE in their project etc.

Also these changes looks like improvements, so not too concerned about users wanting to revert back to older version. But release notes helps with that in case they want to. 👍

**Comment by Monte9** [comment]
:shipit:

**Pull request merged**
