### PR TITLE
fix(Avatar): improve component

### LINKED ISSUE #3742: Letter Avatar throws: WARN  ReactImageView: Image source "null" doesn't exist
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Explain what you did

Using a Letter Avatar: <Avatar containerStyle={styles.drawerHeaderAvatar} rounded size={90} title="CS"/>

### Expected behavior

Not throwing a warning

### Describe the bug

Always logs:  WARN  ReactImageView: Image source "null" doesn't exist

### Steps To Reproduce

```Markdown
Use: <Avatar rounded size={90} title="CS"/>
```

### Screenshots

_No response_

### Your Environment

React Native Elements Env Info
                              
## Global Dependencies:       
                              
   No related dependency found
                              
## Local Dependencies:        
                              
 - @rneui/base : ^4.0.0-rc.7  
 - @rneui/themed : ^4.0.0-rc.7
 - react-native : 0.71.1      
 - @types/react : ^18.0.27

### PR DESCRIPTION
**Pull request by khushal87**
## Motivation

Fixes #3742 and other improvements in the Avatar component (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

- [x] Jest Unit Test
- [x] Checked with `example` app

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation using `yarn docs-build-api`
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

## Additional context

- The `renderPlaceholderContent` and `placeholderStyle` is not relevant anymore because of the change in the implementation of the Avatar component. The previous implementation isn't great. I don't see any use cases for the props as such. Open for suggestions and improvements.

### CODE REVIEW

**Review by kulak91 — APPROVED** [review]

**Comment by khushal87** [comment]
@arpitBhalla can we merge it? What are the plan's to create a merge and release this for the users?

**Comment by arpitBhalla** [comment]
Can you add the changes to migration docs?

**Comment by khushal87** [comment]
This https://reactnativeelements.com/docs/migration_guide? @arpitBhalla

**Comment by arpitBhalla** [comment]
Yes. https://reactnativeelements.com/migration/migration-v3 this to be more specific

**Comment by arpitBhalla** [comment]
@khushal87 can you update docs in another PR

**Comment by khushal87** [comment]
> @khushal87 can you update docs in another PR

Sure, I will do it, this weekend.

**Pull request merged**
