### PR TITLE
feat: added whatsapp and facebook-messenger to SocialIcons

### PR DESCRIPTION
**Pull request by codakkk**
Two new social icons added to SocialIcons component: facebook-messenger and WhatsApp.

### CODE REVIEW

**Comment by flyingcircle** [comment]
@codakkk I just pushed a large change, can you pull in those changes to clean up this PR?

**Review by flyingcircle — CHANGES_REQUESTED** [review]
As commented above.

**Comment by abhishekkumar08** [comment]
Hey @flyingcircle , as I think the contributor is inactive can I make the required the changes and make a new PR?

**Comment by flyingcircle** [comment]
@abhishekkumar08 go for it

**Pull request closed without merging**
