### PR TITLE
fix: @ts-ignores from withTheme.tsx

### PR DESCRIPTION
**Pull request by namantayal**
**What kind of change does this PR introduce?**

fix

**Did you add tests for your changes?**
no
**If relevant, did you update the documentation?**
no
**Summary**

**Does this PR introduce a breaking change?**
no

**Other information**

### CODE REVIEW

**Comment by arpitBhalla** [comment]
great you don't used ```as any```  directly😅

**Comment by namantayal** [comment]
@arpitBhalla have I done anything wrong? I am not very experienced in typescript but trying my best. If anything is incorrect please let me know.

**Comment by arpitBhalla** [comment]
https://github.com/react-native-elements/react-native-elements/issues/2798#issuecomment-798712933

Check this

**Comment by namantayal** [comment]
@arpitBhalla thanks

**Pull request closed without merging**
