### PR TITLE
fix: ThemeProvider re-render on prop change

### LINKED ISSUE #2571: Bug(ThemeProvider): Toggling useDark prop doesn't updates the theme.
**Description**
While working on a feature of enabling dark mode by toggling a `Switch` which in turn changes the prop of the `ThemeProvider`. After successfully changing the `prop` the theme didn't get updated.

**Expected Behaviour**
The theme must update on the change of prop.

### PR DESCRIPTION
**Pull request by pranshuchittora**
Closes #2571

### CODE REVIEW

**Review by flyingcircle — APPROVED** [review]

**Comment by pranshuchittora** [comment]
Need to modify in order to improve performance.

**Comment by pranshuchittora** [comment]
I have implemented this feature to listen to `prop` changes.
On toggling the switch the prop changes which in turn changes the theme.
<div>



<div>

:)

**Review by flyingcircle — APPROVED** [review]

**Comment by IlyaSemenov** [comment]
@pranshuchittora Your PR has broken custom theming support. All custom colors are lost after switching to dark mode (see #2647). Will you please come up with a fix?

**Comment by vividh** [comment]
@pranshuchittora I fixed this in https://github.com/react-native-elements/react-native-elements/pull/2650. Please take a look when you get time.

**Pull request merged**
