### PR TITLE
LinearProgress Documentation

### PR DESCRIPTION
**Pull request by arpitBhalla**
**What kind of change does this PR introduce?**

Added Documentation for LinearProgress Component

### CODE REVIEW

**Comment by arpitBhalla** [comment]
@flyingcircle  Kindly Review

**Comment by flyingcircle** [comment]
Adding a gif like you had in the other PR would be a good addition so that people can see what it looks like.

**Review by flyingcircle — CHANGES_REQUESTED** [review]
Like you can see here: https://reactnativeelements.com/docs/divider#props It would be good to tell users that the component receives all `View` props.

**Comment by arpitBhalla** [comment]
@flyingcircle Sir I mistakenly pushed older file, Can You please add this to `website/docs/props/linearProgress.md` I am sorry for this

```markdown
## Props

> Also receives all
> [View](https://reactnative.dev/docs/view#props) props

- [`value`](#value)
- [`variant`](#variant)
- [`style`](#style)
- [`color`](#color)
- [`trackColor`](#trackColor)

---

## Reference

### `value`

The value of the progress indicator for the determinate variant. Value between 0 and 1.

|  Type  | Default |
| :----: | :-----: |
| number |    0    |

---

### `variant`

Type of button (optional)

|              Type              |    Default    |
| :----------------------------: | :-----------: |
| `determinate`, `indeterminate` | indeterminate |

---

### `style`

add additional styling for linear progress component (optional)

|        Type         | Default |
| :-----------------: | :-----: |
| View style (object) |  none   |

---

### `color`

color for linear progress

|                       Type                       |  Default  |
| :----------------------------------------------: | :-------: |
| `primary`,`secondary` <br/>**OR**<br/>color name | secondary |

---

### `trackColor`

Track color for linear progress

|  Type  |          Default          |
| :----: | :-----------------------: |
| string | `color` with transparency |

---

```

**Pull request merged**
