### PR TITLE
fix issue with listItem alignItems center

### LINKED ISSUE #2396: ListItem & alignItems center - #1142 is not fixed
**Explain what you did**

I reproduced #1142 by placing a ListItem in a View that had the style property `alignItems: 'center'`.

**Expected behavior**

The ListItem will display all of its contents

**Describe the bug**

The ListItem displays none of its contents.

**To Reproduce**

See matching screenshots below.

Initial View:
```javascript
      <View style={{ backgroundColor: 'red' }}>
        <ListItem title="Test" />
      </View>
```
With centering:
```javascript
      <View style={{ alignItems: 'center', backgroundColor: 'red' }}>
        <ListItem title="Test" />
      </View>
```
Removing flex from `contentContainer`.  This seems to fix at least the whole container being shown, but the icons don't seem to show up if added.
```javascript
      <View style={{ alignItems: 'center', backgroundColor: 'red' }}>
        <ListItem title="Test" contentContainerStyle={{ flex: 0 }} />
      </View>
```

**Screenshots**
Screen Shot 2020-06-16 at 1 34 17 PM
Screen Shot 2020-06-16 at 1 34 26 PM
Screen Shot 2020-06-16 at 1 34 41 PM

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    `^1.2.7`     |
| react-native          |    `0.62.2`     |

### PR DESCRIPTION
**Pull request by flyingcircle**
Fixes #2396

### CODE REVIEW

**Comment by flyingcircle** [comment]
@alburdette619 Can you verify this fix?

**Comment by blueberry6401** [comment]
Hi, when will this issue get fixed? Any workaround for now?

**Comment by flyingcircle** [comment]
@blueberry6401 the workaround is to use `alignSelf: center` on your `ListItem`. Changing around the `alignItems` had too many down stream effects.

**Comment by mehradae** [comment]
This work around is not working and the problem still exists. Do we have a better solution?

**Pull request merged**
