### PR TITLE
Fix: Remove problem causing conditional checks in styling

### PR DESCRIPTION
**Pull request by rishabhsxn**
* Due to these conditional checks height, width and borderRadius are not calculated dynamically, instead are using hardcoded values
* Fix: SocialIcon rendered as button when props raised={false} and light={true}
* Fix: Whole icon not resizing according to passed prop iconSize when raised={true} (Only inner symbol resizes)

**What kind of change does this PR introduce?**
Bug fix for issue #3065 and #3066 

**Did you add tests for your changes?**
No. I am new to open-source contribution and not know much about testing.
However, the test suites need to be modified as the snapshots contain the old borderRadius value i.e. 30 (which was hardcoded). Now the borderRadius will be dynamically calculated depending upon the value of prop iconSize, so that the whole icon will resize based on iconSize.

**If relevant, did you update the documentation?**
Not relevant.

**Summary**
This PR implements bug fixes for above mentioned issues. 
Motivation: I was trying to resize the SocialIcon in my project but only inner symbol was resizing. So I checked the source code and tried to figure out what styles were being applied. I found out that the whole icon was properly resizing when I set raised={false}. In the process I also found that if I make raised={false} and light={true}, the component becomes a button type which should not happen if button={true} is not set.
I already opened the issues.

**Does this PR introduce a breaking change?**
No.

**Other information**
Screenshot of test suite that needs to be modified to accomodate the dynamic calculation of borderRadius:
image

### CODE REVIEW

**Review by khushal87 — COMMENTED** [review]
@rishabhsxn Please make sure all the checks pass. To update the snapshot you can run `yarn test -u` , this will automatically update the snapshots. Make sure after this your `yarn test` passes. Feel free to reach out for issues.

**Comment by rishabhsxn** [comment]
I updated the test snapshot and ran ```yarn test```
Looks like all tests were passed.
image

Let me know if something is incorrect.

**Comment by khushal87** [comment]
@rishabhsxn I think you need to solve the prettier issues:
```
/home/travis/build/react-native-elements/react-native-elements/src/social/SocialIcon.tsx
  147:11  error  Delete `··`  prettier/prettier
  148:1   error  Delete `··`  prettier/prettier
  149:11  error  Delete `··`  prettier/prettier
  150:1   error  Delete `··`  prettier/prettier
```

**Comment by rishabhsxn** [comment]
@khushal87 Looks like this issue is related to line endings (LF and CRLF) or whitespaces. I am using VS code on a windows machine.
I can't generate this error on my local machine. Is there any other way to check if the error is solved without commiting and pushing the code?

**Comment by khushal87** [comment]
@rishabhsxn Now there are no issues.

**Comment by flyingcircle** [comment]
This solution doesn't make sense to me. If you add `button`, then the problem still appears with odd shaped social icons. Plus the `iconSize` prop would no longer be resizing the `icon` button the entire component, which doesn't seem correct to me.

**Comment by rishabhsxn** [comment]
@flyingcircle  Could you elaborate " then the problem still appears with odd shaped social icons"  ?

Why would anyone want to increase or decrease the size of inner symbol of SocialIcon with iconSize and not changing the size of whole SocialIcon? A user would consider SocialIcon as an icon not as a component containing an icon.

**Pull request closed without merging**
