### PR TITLE
fix: remove React.PropTypes since deprecated

### PR DESCRIPTION
**Pull request by flyingcircle**
Fixes: #2257 
Also depends on a fixed version of RN-ratings: https://github.com/Monte9/react-native-ratings/pull/91
@Monte9

### CODE REVIEW

**Comment by mafortier-nexapp** [comment]
@flyingcircle In react-native-web, classes in styles coming from a StyleSheet are exported as a number.

These style props like this `containerStyle: PropTypes.object` will throw and crash:

image

**Comment by flyingcircle** [comment]
@mafortier-nexapp that's a warning, not a crash. Do you have info on what was causing the crash?

**Comment by mafortier-nexapp** [comment]
@flyingcircle you're right, that was not the cause of our crash. It's just a warning, don't mind my comment 😄

**Comment by AzzouDuGhetto** [comment]
@flyingcircle I get a new warning after upgrading to 2.0.1 because of this change in Avatar.js: 
```
 - source: RNImage.propTypes.source,
 + source: PropTypes.node,
```

The warning is 
image

**Comment by flyingcircle** [comment]
@AzzouDuGhetto `RNImage.propTypes.source` was deprecated in RN 62 and was throwing an error when using RN-web 12. I'll open a ticket on how to better fix this for 2.0.2

**Pull request merged**
