### PR TITLE
[ListItem] Added New Sub Component: ListItem Swipeable 

### PR DESCRIPTION
**Pull request by arpitBhalla**
- [x] Component
- [x] Docs
- [x] Demo

### CODE REVIEW

**Comment by arpitBhalla** [comment]
@flyingcircle Kindly Review

**Comment by khushal87** [comment]
@arpitBhalla LGTM 😄

**Comment by zhangkai-cpchain** [comment]
There's a spelling mistake in the docs (https://reactnativeelements.com/docs/listitem). ListItem.Swipable => ListItem.Swip**e**able

**Comment by arpitBhalla** [comment]
> There's a spelling mistake in the docs (https://reactnativeelements.com/docs/listitem). ListItem.Swipable => ListItem.Swip**e**able

Has been resolved already

**Comment by 0xouzm** [comment]
How can I reset the swiped-list after I press the button? I can't find any docs here...

**Comment by arpitBhalla** [comment]
#3411

**Pull request merged**
