### PR TITLE
fix slider for web

### PR DESCRIPTION
**Pull request by CHaNGeTe**
For me, it solves https://github.com/react-native-elements/react-native-elements/issues/1890

### CODE REVIEW

**Comment by renanmav** [comment]
Any update on this?

**Comment by belgamo** [comment]
Any?

**Comment by KirillCherkalov** [comment]
Hi guys. A forked this RP and made changes for react-native-elements on version 2.0.2
https://github.com/KirillCherkalov/react-native-elements/pull/1/files

**Comment by flyingcircle** [comment]
Closing in favor of #2465

**Comment by flyingcircle** [comment]
@CHaNGeTe message me on the React-native-elements Slack. I'd like to send you a token payment for this fix.

**Pull request closed without merging**
