### PR TITLE
website: add missing dependencies 

### PR DESCRIPTION
**Pull request by MaximFedarau**
Before: after dependencies installation and starting the website it broke with 30! errors.
Now: everything works.

## Motivation

Fixes bug with the launch of the website (website didn't launch at all!).

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- [x] Jest Unit Test
- [x] Checked with `example` app

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by MaximFedarau** [comment]
@arpitBhalla

**Comment by MaximFedarau** [comment]
@arpitBhalla

**Comment by arpitBhalla** [comment]
Can you share the issue you were facing?

**Comment by MaximFedarau** [comment]
## Actions
1) cd `website`;
2) run `yarn`;
3) run `yarn start`;

## Errors
Have 30 compile errors:
-  `Can't resolve buffer in PATH_ON_MY_COMPUTER`;
- `Can't resolve process/browser`.

## My patch fixes BOTH errors in all places.

**Comment by MaximFedarau** [comment]
Hey, @arpitBhalla, there is some demo for both cases:
## Before fix:

### Work with console:
https://user-images.githubusercontent.com/87207122/195899469-2b4e1869-1575-4bd8-ac4f-34d2960446e6.mp4

### Website itself:
photo_fail


## After fix:

### Work with console:
https://user-images.githubusercontent.com/87207122/195899705-6738230f-40b1-47c5-8007-50e7f2ce647a.mov

### Website itself:
photo_success

**Comment by arpitBhalla** [comment]
Hey, it's bit weird you are getting this error, `assert`, `process` and `buffer` are already there in node, try upgrading/reinstalling node maybe?

**Comment by MaximFedarau** [comment]
Tried it.
It's not working.

**Comment by MaximFedarau** [comment]
Also I has the latest node: `v18.10.0`.

**Comment by MaximFedarau** [comment]
@arpitBhalla, just ran website in Docker container.
It has the same error.

**Comment by MaximFedarau** [comment]
# 🐳Docker test🐳

## Before fix:

```
docker logs 8f28eca7110e26c8bde5841de194c6b38708ef8d50938d902f15e43960fcbc65
```

```
[INFO] Starting the development server...
[SUCCESS] Docusaurus website is running at http://localhost:3000/.
ℹ Compiling Client
✔ Client: Compiled with some errors in 50.00s


Module not found: Error: Can't resolve 'process/browser' in '/app/website/node_modules/@babel/code-frame/lib'
Module not found: Error: Can't resolve 'process/browser' in '/app/website/node_modules/@babel/core/lib/config/helpers'
Module not found: Error: Can't resolve 'buffer' in '/app/website/node_modules/@babel/generator/node_modules/jsesc'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "buffer": require.resolve("buffer/") }'
        - install 'buffer'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "buffer": false }
Module not found: Error: Can't resolve 'process/browser' in '/app/website/node_modules/@babel/helper-compilation-targets/lib'
Module not found: Error: Can't resolve 'assert' in '/app/website/node_modules/@babel/helper-module-imports/lib'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "assert": require.resolve("assert/") }'
        - install 'assert'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "assert": false }
Module not found: Error: Can't resolve 'assert' in '/app/website/node_modules/@babel/helper-module-imports/lib'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "assert": require.resolve("assert/") }'
        - install 'assert'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "assert": false }
Module not found: Error: Can't resolve 'assert' in '/app/website/node_modules/@babel/helper-module-transforms/lib'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "assert": require.resolve("assert/") }'
        - install 'assert'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "assert": false }
Module not found: Error: Can't resolve 'assert' in '/app/website/node_modules/@babel/helper-module-transforms/lib'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "assert": require.resolve("assert/") }'
        - install 'assert'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "assert": false }
Module not found: Error: Can't resolve 'process/browser' in '/app/website/node_modules/@babel/highlight/node_modules/chalk'
Module not found: Error: Can't resolve 'process/browser' in '/app/website/node_modules/@babel/types/lib/definitions'
Module not found: Error: Can't resolve 'process/browser' in '/app/website/node_modules/@babel/types/lib/definitions'
Module not found: Error: Can't resolve 'process/browser' in '/app/website/node_modules/@babel/types/lib/definitions'
Module not found: Error: Can't resolve 'process/browser' in '/app/website/node_modules/@docusaurus/core/node_modules/semver/internal'
Module not found: Error: Can't resolve 'buffer' in '/app/website/node_modules/@jridgewell/sourcemap-codec/dist'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "buffer": require.resolve("buffer/") }'
        - install 'buffer'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "buffer": false }
Module not found: Error: Can't resolve 'assert' in '/app/website/node_modules/@miksu/prettier/lib/common'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "assert": require.resolve("assert/") }'
        - install 'assert'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "assert": false }
Module not found: Error: Can't resolve 'assert' in '/app/website/node_modules/@miksu/prettier/lib/language-js'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "assert": require.resolve("assert/") }'
        - install 'assert'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "assert": false }
Module not found: Error: Can't resolve 'assert' in '/app/website/node_modules/@miksu/prettier/lib/language-js'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "assert": require.resolve("assert/") }'
        - install 'assert'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "assert": false }
Module not found: Error: Can't resolve 'assert' in '/app/website/node_modules/@miksu/prettier/lib/main'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "assert": require.resolve("assert/") }'
        - install 'assert'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "assert": false }
Module not found: Error: Can't resolve 'process/browser' in '/app/website/node_modules/@miksu/prettier/lib/main'
Module not found: Error: Can't resolve 'assert' in '/app/website/node_modules/@miksu/prettier/lib/main'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "assert": require.resolve("assert/") }'
        - install 'assert'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "assert": false }
Module not found: Error: Can't resolve 'process/browser' in '/app/website/node_modules/@miksu/prettier/lib/main'
Module not found: Error: Can't resolve 'process/browser' in '/app/website/node_modules/@miksu/prettier/node_modules/@babel/code-frame/lib'
Module not found: Error: Can't resolve 'process/browser' in '/app/website/node_modules/@miksu/prettier/node_modules/chalk'
Module not found: Error: Can't resolve 'buffer' in '/app/website/node_modules/@philpl/buble/dist'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "buffer": require.resolve("buffer/") }'
        - install 'buffer'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "buffer": false }
Module not found: Error: Can't resolve 'process/browser' in '/app/website/node_modules/browserslist'
Module not found: Error: Can't resolve 'buffer' in '/app/website/node_modules/convert-source-map/node_modules/safe-buffer'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "buffer": require.resolve("buffer/") }'
        - install 'buffer'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "buffer": false }
Module not found: Error: Can't resolve 'process/browser' in '/app/website/node_modules/debug/src'
Module not found: Error: Can't resolve 'process/browser' in '/app/website/node_modules/path-browserify'
Module not found: Error: Can't resolve 'process/browser' in '/app/website/node_modules/vnopts/node_modules/chalk'
Module not found: Error: Can't resolve 'process/browser' in '/app/website/node_modules/webpack-dev-server/client/modules/logger'
client (webpack 5.72.1) compiled with 30 errors
```

## Now:
```
docker logs 3f960e3b8552fff6f8baaa4bfdc506a08d573a712c68f03bb2659dc718cf7515
```

```
[INFO] Starting the development server...
[SUCCESS] Docusaurus website is running at http://localhost:3000/.
ℹ Compiling Client
✔ Client: Compiled successfully in 55.58s
client (webpack 5.72.1) compiled successfully
```

**Comment by MaximFedarau** [comment]
Hey, @arpitBhalla.
In general fix:
- [x] solves the issue on local computer
- [x] solves the issue in Docker container
- [x] passes all checks.

Will you merge this pr?😅

**Comment by arpitBhalla** [comment]
Hey, i have to manually update `yarn.lock` file

**Review by arpitBhalla — APPROVED** [review]

**Comment by MaximFedarau** [comment]
@arpitBhalla, I just saw, that `yarn.lock` updates (rewrites) automatically after running `yarn` command.

**Comment by arpitBhalla** [comment]
> @arpitBhalla, I just saw, that `yarn.lock` updates (rewrites) automatically after running `yarn` command.

Yep I am aware of that, was making sure no miscellaneous pkg was added via lock file.

**Pull request merged**
