### PR TITLE
(website): Update script for InlinePressableProps

### PR DESCRIPTION
**Pull request by khushal87**
This PR fixes the issue with the `InlinePressableProps` which is under the `src/helpers` directory. This makes the pressableProps to be rendered with the documentation.

### CODE REVIEW

**Comment by arpitBhalla** [comment]
Screenshot-20210830160902-659x431

**Comment by khushal87** [comment]
> Multiple _prop description_
> Screenshot-20210830160902-659x431

@arpitBhalla I suppose I comment on the PR #3187 to fix them in docgenParser.ts.  I don't know the best possible types for these props as you have worked on them. So please add conditions for them in your PR or create a new PR if that is merged to fix them. Adding conditions for them is the best possible way for now to fix them. And, I am not aware of the exact type if this is replaced. So, I asked you to work on them in your PR. Please look at it. The docgen is working fine as it is supposed to be.

**Comment by khushal87** [comment]
> Multiple _prop description_
> Screenshot-20210830160902-659x431

This is because these props are already present in pressable props provided by React Native. The description inside node_modules and the added description by you are merged. Please remove your added prop to make this work. As the props are overlapping with the same name and do not make any sense.

**Comment by arpitBhalla** [comment]
> Please remove your added prop to make this work

?

**Comment by khushal87** [comment]
Screenshot from 2021-09-03 11-20-40
@arpitBhalla The history shows that you have added the description here. What I mean is that, if react docgen typescript detects two same props(intersecting props).

Here:
One inside `PressableProps` inside /react-native-elements/node_modules/@types/react-native/index.d.ts:
```
export type InlinePressableProps = Inline<
  PressableProps,
  'onPress' | 'onLongPress' | 'onPressIn' | 'onPressOut'
>;
```
having description `Called when a long-tap gesture is detected.`
and the other in lines 25-26 of Image.tsx
```
/** Callback function when long pressing component. */
    onLongPress?(): void;
```
having description `Callback function when long-pressing component.`.

As there are the same props with two descriptions react-docgen-typescript is merging their descriptions. 
The solution is to remove the `onLongPress` from the component props as it is already in `PressableProps` you have imported.

**Comment by arpitBhalla** [comment]
> @arpitBhalla The history shows that you have added the description here.

Kindly check again and see carefully in #3145 

https://github.com/react-native-elements/react-native-elements/pull/3145/files#diff-9d5b5c3f693360668dda73e10258f9cf27ca4788fd30821a0ba70aadfe4d46f3R21-R25

**Comment by khushal87** [comment]
> > @arpitBhalla The history shows that you have added the description here.
> > why do we need it again in component props?
> 
> Kindly check again in https://github.com/react-native-elements/react-native-elements/pull/3145/files#diff-9d5b5c3f693360668dda73e10258f9cf27ca4788fd30821a0ba70aadfe4d46f3R21-R25
> 
> Can we make something to overwrite the parent description?

I will have to think about that. Do you have a solution?

**Comment by arpitBhalla** [comment]
No ;)

**Comment by khushal87** [comment]
> No ;)

Can we remove the prop from Image.tsx as it is already present?

**Comment by arpitBhalla** [comment]
@khushal87 Can you merge `next` ?

**Pull request merged**
