### PR TITLE
docs(Button): fix typos

### PR DESCRIPTION
**Pull request by MaximFedarau**
## Motivation

Fix punctuation, remove link leading nowhere, repeated words.

## Type of change

Docs fix.

# How Has This Been Tested?

- [x] Jest Unit Test
- [x] Checked with `example` app

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by MaximFedarau** [comment]
@arpitBhalla, update docs, so only docs check fails. I think it's ok?

**Comment by MaximFedarau** [comment]
@arpitBhalla, update docs, so only docs check fails. I think it's ok?

**Comment by arpitBhalla** [comment]
Docs are auto generated, fix typos in component file in `packages/base`

**Comment by MaximFedarau** [comment]
@arpitBhalla, thanks. Done.

**Comment by MaximFedarau** [comment]
@arpitBhalla, all tests are ok.

**Comment by MaximFedarau** [comment]
Hey, @arpitBhalla , all tests are ok.

**Comment by MaximFedarau** [comment]
@arpitBhalla , fixed all merge conflicts

**Comment by arpitBhalla** [comment]
Hey, there's some issue with docs build, will merge this after that.

**Pull request merged**
