### PR TITLE
Docs [SocialIcon]: add missing prop activityIndicatorStyle

### PR DESCRIPTION
**Pull request by ankushdutt**
`activityIndicatorStyle` prop is present in the SocialIcon code but missing from the documentation website.

### CODE REVIEW

**Comment by flyingcircle** [comment]
The docs should be in alphabetical order. Please change that around.

**Comment by ankushdutt** [comment]
> The docs should be in alphabetical order. Please change that around.

Ah, sorry, I have changed the order now.

**Comment by flyingcircle** [comment]
Remove the change to the versioned file to resolve the conflict.

**Comment by ankushdutt** [comment]
> Remove the change to the versioned file to resolve the conflict.

Done

**Pull request merged**
