### PR TITLE
[Refactor] docs directory structure

### PR DESCRIPTION
**Pull request by khushal87**
**What kind of change does this PR introduce?**
Improvises the docs directory structure such that the fixed files are maintained under respective folders.

**Did you add tests for your changes?**
Not required
**If relevant, did you update the documentation?**
Yes, I have refactored the documentation itself.
**Summary**
This introduces 3 new folders separating `main, universe, repo` docs and having the markdown files within the respective folders.

**Does this PR introduce a breaking change?**
No.

**Other information**
Not required.

### CODE REVIEW

**Review by arpitBhalla — CHANGES_REQUESTED** [review]
> 

**What kind of change does this PR introduce?**
Improvises the docs directory structure such that the fixed files are maintained under respective folders.


**Did you add tests for your changes?**
Not required
**If relevant, did you update the documentation?**
Yes, I have refactored the documentation itself.
**Summary**
This introduces 3 new folders separating `basic, main, universe, repo` docs and having the markdown files within the respective folders.



**Does this PR introduce a breaking change?**
No.


**Other information**
Not required.

**Review by arpitBhalla — APPROVED** [review]

**Review by arpitBhalla — APPROVED** [review]

**Comment by arpitBhalla** [comment]
@khushal87 Sorry its by mistake

**Comment by pranshuchittora** [comment]
Can you briefly explain about all theses `basic, main, universe, repo`

**Comment by arpitBhalla** [comment]
@pranshuchittora Can we do like this?
image

**Comment by khushal87** [comment]
@pranshuchittora Basically the docs directory has all the docs in the same directory. What I have done is that I have segregated the docs on the basis of purpose.
- The universe directory has the universe components docs and props.
- The main directory has the main package props and docs.
- The repo directory has the contributing guidelines and stuff.

The purpose of doing this is that when the documentation would be generated automatically, the main folder will have the package-related documentation and the other two are left un-hampered.

**Comment by khushal87** [comment]
@arpitBhalla Thanks for your views, currently the docs have the same pattern. I will obviously add nesting for compound components :)

**Comment by pranshuchittora** [comment]
```
The universe directory has the universe components docs and props.
The main directory has the main package props and docs.
The repo directory has the contributing guidelines and stuff.
```

This looks great. We need to make the following changes in the Playground as well because it fetches these docs on build time. Else looks good to me

**Comment by khushal87** [comment]
Okay, I will check that too, I was a bit zoned out about the playground for the following change.

**Review by pranshuchittora — APPROVED** [review]

**Pull request merged**
