### PR TITLE
feat(tooling): Reduced package size by removing unwanted files in the tar.

### LINKED ISSUE #2569: tooling: Reduce package size by 63% by shipping only the required files in the build.
<details><summary>Current Build (Unpacked Size : 637.8 kB)</summary><pre>npm pack --dry-run
npm notice 
npm notice 📦  react-native-elements@2.3.2
npm notice === Tarball Contents === 
npm notice 114B   .editorconfig                                                  
npm notice 17B    .eslintignore                                                  
npm notice 100B   .eslintrc                                                      
npm notice 75B    .prettierrc                                                    
npm notice 1.1kB  LICENSE                                                        
npm notice 602B   src/avatar/__tests__/Accessory.js                              
npm notice 1.9kB  src/avatar/Accessory.js                                        
npm notice 6.5kB  src/avatar/__tests__/Avatar.js                                 
npm notice 5.7kB  src/avatar/Avatar.js                                           
npm notice 77B    babel.config.js                                                
npm notice 139B   src/config/BackgroundImage.js                                  
npm notice 3.8kB  src/badge/__tests__/Badge.js                                   
npm notice 2.1kB  src/badge/Badge.js                                             
npm notice 2.8kB  src/bottomSheet/__tests__/BottomSheet.js                       
npm notice 1.6kB  src/bottomSheet/BottomSheet.js                                 
npm notice 5.3kB  src/buttons/__tests__/Button.js                                
npm notice 7.3kB  src/buttons/Button.js                                          
npm notice 6.3kB  src/buttons/__tests__/ButtonGroup.js                           
npm notice 7.4kB  src/buttons/ButtonGroup.js                                     
npm notice 2.8kB  src/card/__tests__/Card.js                                     
npm notice 6.3kB  src/card/Card.js                                               
npm notice 414B   src/card/CardDivider.js                                        
npm notice 759B   src/card/CardFeaturedSubtitle.js                               
npm notice 744B   src/card/CardFeaturedTitle.js                                  
npm notice 397B   src/card/CardImage.js                                          
npm notice 1.1kB  src/card/CardTitle.js                                          
npm notice 4.2kB  src/checkbox/__tests__/CheckBox.js                             
npm notice 3.5kB  src/checkbox/CheckBox.js                                       
npm notice 1.3kB  src/checkbox/CheckBoxIcon.js                                   
npm notice 948B   src/config/colors.js                                           
npm notice 936B   src/config/colorsDark.js                                       
npm notice 6.9kB  src/searchbar/__tests__/common.js                              
npm notice 1.5kB  src/divider/__tests__/Divider.js                               
npm notice 619B   src/divider/Divider.js                                         
npm notice 2.8kB  src/tile/__tests__/FeaturedTile.js                             
npm notice 3.8kB  src/tile/FeaturedTile.js                                       
npm notice 890B   src/config/fonts.js                                            
npm notice 764B   src/helpers/getIconStyle.js                                    
npm notice 1.9kB  src/helpers/getIconType.js                                     
npm notice 4.0kB  src/tooltip/getTooltipCoordinate.js                            
npm notice 5.7kB  src/header/__tests__/Header.js                                 
npm notice 5.4kB  src/header/Header.js                                           
npm notice 3.4kB  src/icons/__tests__/Icon.js                                    
npm notice 4.2kB  src/icons/Icon.js                                              
npm notice 3.6kB  src/image/__tests__/Image.js                                   
npm notice 4.0kB  src/image/Image.js                                             
npm notice 430B   src/config/index.js                                            
npm notice 776B   src/helpers/index.js                                           
npm notice 2.0kB  src/index.js                                                   
npm notice 7.5kB  src/input/__tests__/Input.js                                   
npm notice 5.9kB  src/input/Input.js                                             
npm notice 3.2kB  src/list/__tests__/ListItem.js                                 
npm notice 11.3kB src/list/ListItem.js                                           
npm notice 532B   src/list/ListItemButtonGroup.js                                
npm notice 524B   src/list/ListItemCheckBox.js                                   
npm notice 633B   src/list/ListItemChevron.js                                    
npm notice 653B   src/list/ListItemContent.js                                    
npm notice 912B   src/list/ListItemInput.js                                      
npm notice 857B   src/list/ListItemSubtitle.js                                   
npm notice 801B   src/list/ListItemTitle.js                                      
npm notice 155B   src/helpers/nodeType.js                                        
npm notice 2.4kB  src/helpers/normalizeText.js                                   
npm notice 1.9kB  src/overlay/__tests__/Overlay.js                               
npm notice 2.3kB  src/overlay/Overlay.js                                         
npm notice 4.3kB  src/pricing/__tests__/PricingCard.js                           
npm notice 4.5kB  src/pricing/PricingCard.js                                     
npm notice 725B   src/helpers/renderNode.js                                      
npm notice 218B   src/searchbar/__tests__/SearchBar-android.js                   
npm notice 5.2kB  src/searchbar/SearchBar-android.js                             
npm notice 165B   src/searchbar/__tests__/SearchBar-default.js                   
npm notice 5.7kB  src/searchbar/SearchBar-default.js                             
npm notice 210B   src/searchbar/__tests__/SearchBar-ios.js                       
npm notice 7.8kB  src/searchbar/SearchBar-ios.js                                 
npm notice 3.1kB  src/searchbar/__tests__/SearchBar.js                           
npm notice 1.1kB  src/searchbar/SearchBar.js                                     
npm notice 8.0kB  src/slider/__tests__/Slider.js                                 
npm notice 17.1kB src/slider/Slider.js                                           
npm notice 3.4kB  src/social/__tests__/SocialIcon.js                             
npm notice 5.2kB  src/social/SocialIcon.js                                       
npm notice 2.9kB  src/text/__tests__/Text.js                                     
npm notice 2.0kB  src/text/Text.js                                               
npm notice 62B    src/config/theme.js                                            
npm notice 1.4kB  src/config/__tests__/ThemeProvider.js                          
npm notice 1.4kB  src/config/ThemeProvider.js                                    
npm notice 2.9kB  src/tile/__tests__/Tile.js                                     
npm notice 4.1kB  src/tile/Tile.js                                               
npm notice 973B   src/tooltip/__tests__/Tooltip.android.js                       
npm notice 6.2kB  src/tooltip/__tests__/Tooltip.js                               
npm notice 8.3kB  src/tooltip/Tooltip.js                                         
npm notice 811B   src/tooltip/Triangle.js                                        
npm notice 438B   src/helpers/types.js                                           
npm notice 1.6kB  src/badge/__tests__/withBadge.js                               
npm notice 1.3kB  src/badge/withBadge.js                                         
npm notice 1.6kB  src/config/__tests__/withTheme.js                              
npm notice 2.0kB  src/config/withTheme.js                                        
npm notice 3.4kB  package.json                                                   
npm notice 15.8kB README.md                                                      
npm notice 252B   src/avatar/__tests__/__snapshots__/Accessory.js.snap           
npm notice 14.8kB src/avatar/__tests__/__snapshots__/Avatar.js.snap              
npm notice 6.2kB  src/badge/__tests__/__snapshots__/Badge.js.snap                
npm notice 11.8kB src/bottomSheet/__tests__/__snapshots__/BottomSheet.js.snap    
npm notice 12.2kB src/buttons/__tests__/__snapshots__/Button.js.snap             
npm notice 28.7kB src/buttons/__tests__/__snapshots__/ButtonGroup.js.snap        
npm notice 6.0kB  src/card/__tests__/__snapshots__/Card.js.snap                  
npm notice 19.2kB src/checkbox/__tests__/__snapshots__/CheckBox.js.snap          
npm notice 775B   src/divider/__tests__/__snapshots__/Divider.js.snap            
npm notice 11.1kB src/tile/__tests__/__snapshots__/FeaturedTile.js.snap          
npm notice 8.0kB  src/header/__tests__/__snapshots__/Header.js.snap              
npm notice 7.6kB  src/icons/__tests__/__snapshots__/Icon.js.snap                 
npm notice 8.1kB  src/image/__tests__/__snapshots__/Image.js.snap                
npm notice 19.0kB src/input/__tests__/__snapshots__/Input.js.snap                
npm notice 6.2kB  src/list/__tests__/__snapshots__/ListItem.js.snap              
npm notice 5.2kB  src/overlay/__tests__/__snapshots__/Overlay.js.snap            
npm notice 15.4kB src/pricing/__tests__/__snapshots__/PricingCard.js.snap        
npm notice 16.5kB src/searchbar/__tests__/__snapshots__/SearchBar-android.js.snap
npm notice 12.8kB src/searchbar/__tests__/__snapshots__/SearchBar-default.js.snap
npm notice 29.4kB src/searchbar/__tests__/__snapshots__/SearchBar-ios.js.snap    
npm notice 5.2kB  src/searchbar/__tests__/__snapshots__/SearchBar.js.snap        
npm notice 9.9kB  src/slider/__tests__/__snapshots__/Slider.js.snap              
npm notice 7.4kB  src/social/__tests__/__snapshots__/SocialIcon.js.snap          
npm notice 534B   src/text/__tests__/__snapshots__/Text.js.snap                  
npm notice 1.5kB  src/config/__tests__/__snapshots__/ThemeProvider.js.snap       
npm notice 10.5kB src/tile/__tests__/__snapshots__/Tile.js.snap                  
npm notice 24.6kB src/tooltip/__tests__/__snapshots__/Tooltip.js.snap            
npm notice 1.7kB  src/badge/__tests__/__snapshots__/withBadge.js.snap            
npm notice 44.2kB src/index.d.ts                                                 
npm notice 636B   .travis.yml                                                    
npm notice === Tarball Details === 
npm notice name:          react-native-elements                   
npm notice version:       2.3.2                                   
npm notice filename:      react-native-elements-2.3.2.tgz         
npm notice package size:  83.9 kB                                 
npm notice unpacked size: 637.8 kB                                
npm notice shasum:        298e2a84b96242504aecb7a6ffcdfb365a9cc6ca
npm notice integrity:     sha512-EMKvsVItZsjnk[...]Nu8lum+8qZ2+A==
npm notice total files:   127                                     
npm notice 
react-native-elements-2.3.2.tgz</pre></details>

<details><summary>After ignoring unwanted files in the package (Unpacked size :  230.7 kB)</summary>
<pre>
 npm pack --dry-run
npm notice 
npm notice 📦  react-native-elements@2.3.2
npm notice === Tarball Contents === 
npm notice 1.1kB  LICENSE                            
npm notice 1.9kB  src/avatar/Accessory.js            
npm notice 5.7kB  src/avatar/Avatar.js               
npm notice 139B   src/config/BackgroundImage.js      
npm notice 2.1kB  src/badge/Badge.js                 
npm notice 1.6kB  src/bottomSheet/BottomSheet.js     
npm notice 7.3kB  src/buttons/Button.js              
npm notice 7.4kB  src/buttons/ButtonGroup.js         
npm notice 6.3kB  src/card/Card.js                   
npm notice 414B   src/card/CardDivider.js            
npm notice 759B   src/card/CardFeaturedSubtitle.js   
npm notice 744B   src/card/CardFeaturedTitle.js      
npm notice 397B   src/card/CardImage.js              
npm notice 1.1kB  src/card/CardTitle.js              
npm notice 3.5kB  src/checkbox/CheckBox.js           
npm notice 1.3kB  src/checkbox/CheckBoxIcon.js       
npm notice 948B   src/config/colors.js               
npm notice 936B   src/config/colorsDark.js           
npm notice 619B   src/divider/Divider.js             
npm notice 3.8kB  src/tile/FeaturedTile.js           
npm notice 890B   src/config/fonts.js                
npm notice 764B   src/helpers/getIconStyle.js        
npm notice 1.9kB  src/helpers/getIconType.js         
npm notice 4.0kB  src/tooltip/getTooltipCoordinate.js
npm notice 5.4kB  src/header/Header.js               
npm notice 4.2kB  src/icons/Icon.js                  
npm notice 4.0kB  src/image/Image.js                 
npm notice 430B   src/config/index.js                
npm notice 776B   src/helpers/index.js               
npm notice 2.0kB  src/index.js                       
npm notice 5.9kB  src/input/Input.js                 
npm notice 11.3kB src/list/ListItem.js               
npm notice 532B   src/list/ListItemButtonGroup.js    
npm notice 524B   src/list/ListItemCheckBox.js       
npm notice 633B   src/list/ListItemChevron.js        
npm notice 653B   src/list/ListItemContent.js        
npm notice 912B   src/list/ListItemInput.js          
npm notice 857B   src/list/ListItemSubtitle.js       
npm notice 801B   src/list/ListItemTitle.js          
npm notice 155B   src/helpers/nodeType.js            
npm notice 2.4kB  src/helpers/normalizeText.js       
npm notice 2.3kB  src/overlay/Overlay.js             
npm notice 4.5kB  src/pricing/PricingCard.js         
npm notice 725B   src/helpers/renderNode.js          
npm notice 5.2kB  src/searchbar/SearchBar-android.js 
npm notice 5.7kB  src/searchbar/SearchBar-default.js 
npm notice 7.8kB  src/searchbar/SearchBar-ios.js     
npm notice 1.1kB  src/searchbar/SearchBar.js         
npm notice 17.1kB src/slider/Slider.js               
npm notice 5.2kB  src/social/SocialIcon.js           
npm notice 2.0kB  src/text/Text.js                   
npm notice 62B    src/config/theme.js                
npm notice 1.4kB  src/config/ThemeProvider.js        
npm notice 4.1kB  src/tile/Tile.js                   
npm notice 8.3kB  src/tooltip/Tooltip.js             
npm notice 811B   src/tooltip/Triangle.js            
npm notice 438B   src/helpers/types.js               
npm notice 1.3kB  src/badge/withBadge.js             
npm notice 2.0kB  src/config/withTheme.js            
npm notice 3.4kB  package.json                       
npm notice 15.8kB README.md                          
npm notice 44.2kB src/index.d.ts                     
npm notice === Tarball Details === 
npm notice name:          react-native-elements                   
npm notice version:       2.3.2                                   
npm notice filename:      react-native-elements-2.3.2.tgz         
npm notice package size:  47.6 kB                                 
npm notice unpacked size: 230.7 kB                                
npm notice shasum:        ecba58ec3104fe6a4e3be4235c6318b5499ad7ea
npm notice integrity:     sha512-/OorAVq4o2Wb0[...]DA7lXH3YmLL7g==
npm notice total files:   62                                      
npm notice 
react-native-elements-2.3.2.tgz
</pre></details>

The proposed solution will reduce the package size by **63.82%**

### PR DESCRIPTION
**Pull request by pranshuchittora**
Close #2569

### CODE REVIEW

**Review by iRoachie — COMMENTED** [review]
Think it might be better to use .npmignore already in use https://github.com/react-native-elements/react-native-elements/blob/next/.npmignore

**Comment by pranshuchittora** [comment]
> Think it might be better to use .npmignore already in use https://github.com/react-native-elements/react-native-elements/blob/next/.npmignore

In our project, we have more to exclude but less to include. Therefore using `fies:` would be the better approach.
And the `files` pattern if officially supported by `npm` as well. -> https://docs.npmjs.com/using-npm/developers.html#testing-whether-your-npmignore-or-files-config-works

**Comment by iRoachie** [comment]
That's a good point!

**Review by flyingcircle — APPROVED** [review]

**Comment by pranshuchittora** [comment]
Removing `.npmignore` as discussed above. Produces the same output.

**Review by flyingcircle — APPROVED** [review]

**Pull request merged**
