### PR TITLE
feat(Slider): Add ability to put an image on the thumb with specific styles. Uses react-native Image.

### PR DESCRIPTION
**Pull request by mcgomez**
Issue for reference: https://github.com/react-native-training/react-native-elements/issues/1394
Checks for optional thumbImage with styling and renders accordingly. Uses react-native [Image](https://facebook.github.io/react-native/docs/image).

### CODE REVIEW

**Comment by mcgomez** [comment]
@iRoachie Hey! All checks have passed, could you take a look at this when you get a chance?

**Comment by iRoachie** [comment]
Have you actually tried running this? This doesn’t do anything for me.

Using::
```jsx
<Slider
  style={{ width: 300 }}
  thumbImage={{
    uri: "https://image.flaticon.com/icons/png/512/55/55369.png"
  }}
/>
```

**Comment by mcgomez** [comment]
@iRoachie Maybe its that url. We are using this PR in our internal project and it works as expected. I'd try with another image url.

**Comment by iRoachie** [comment]
Do you have one that works?

**Comment by mcgomez** [comment]
@iRoachie you could try with https://facebook.github.io/react-native/docs/assets/favicon.png (grabbed from the react native image documentation).

Here's what my slider looks like with that example image and other props set:

```javascript
<Slider
    maximumTrackTintColor={Colors.darkBlue}
    maximumValue={10}
    minimumTrackTintColor={Colors.darkBlue}
    minimumValue={0}
    onValueChange={newValue => {
      ...
    }}
    orientation="vertical"
    step={1}
    thumbImage={{ uri: 'https://facebook.github.io/react-native/docs/assets/favicon.png' }}
    thumbImageStyle={{
      alignSelf: 'center',
      height: 22,
      width: 22,
      marginTop: 18,
    }}
    thumbStyle={{
      width: 60,
      height: 60,
      borderRadius: 30,
      borderWidth: 1,
      borderColor: Colors.teal,
      marginTop: 0,
      top: 0,
    }}
    thumbTouchSize={{ width: 60, height: 60 }}
    thumbTintColor={Colors.background}
    value={valueIndex}
/>
```

**Comment by cmcleese** [comment]
looking forward to this

**Comment by Egizas** [comment]
Is there are plan to merge this?

**Comment by flyingcircle** [comment]
Fixed in #2479

**Pull request closed without merging**
