### PR TITLE
Add testID to CheckBox component typings

### PR DESCRIPTION
**Pull request by stereodenis**

### CODE REVIEW

**Review by reinaldosimoes — APPROVED** [review]
lgtm

**Comment by stereodenis** [comment]
@reinaldosimoes so, what's next?

**Comment by reinaldosimoes** [comment]
@stereodenis the repo owners are the only ones with the ability to merge&deploy so we have to wait :)

**Review by pranshuchittora — APPROVED** [review]
LGTM

**Review by reinaldosimoes — APPROVED** [review]

**Comment by flyingcircle** [comment]
Replaced with #2701

**Pull request closed without merging**
