### PR TITLE
docs: remove npm reference in contributing.md

### PR DESCRIPTION
**Pull request by ersachin3112**
**What kind of change does this PR introduce?**
docs

**Did you add tests for your changes?**
no
**If relevant, did you update the documentation?**
yes
**Summary**

`rpm install` gives error sometimes leading to confusion to new contributors, encourage contributors to use `yarn`

**Does this PR introduce a breaking change?**
no

**Other information**
no

### CODE REVIEW

**Comment by flyingcircle** [comment]
Can you remove the references to `npm` throughout all of the docs? I'd rather have this all solved through a single PR rather than piece-meal for every instance.

**Comment by ersachin3112** [comment]
Sure I will update 👍

**Comment by ersachin3112** [comment]
@flyingcircle done 👍

**Comment by flyingcircle** [comment]
Thanks!

**Pull request merged**
