### PR TITLE
Added new component Dropdown

### PR DESCRIPTION
**Pull request by venishpatidar**
**What kind of change does this PR introduce?**

Introducing a new component Dropdown

**Did you add tests for your changes?**

Yes

**Summary**

Dropdown picker will be added
dropdown

### CODE REVIEW

**Comment by flyingcircle** [comment]
Hmm. I appreciate the PR. I'm not sure how in demand a dropdown list is. It seems like you'd want to use the `ListItem` that we already have to build something like this out. The other concern I have with this is that it looks out of place. It doesn't look like any of the other components.

**Comment by venishpatidar** [comment]
#253 `https://github.com/react-native-elements/react-native-elements/issues/253`
It would be pretty handy as RNE lacks of dropdown, therefore it needed to install another package specifically for dropdown. Is there anything that you want to be get upgraded, removed or edited, I would like to accept any suggestion.

**Comment by flyingcircle** [comment]
Yeah a dropdown would be a fine addition. But right now, it looks like a DOS menu or something. It needs to look like an RNE component. Try using `ListItem` in the component instead.

**Comment by venishpatidar** [comment]
I am on it 👍.

**Comment by HariAcidReign** [comment]
> Yeah a dropdown would be a fine addition. But right now, it looks like a DOS menu or something. It needs to look like an RNE component. Try using `ListItem` in the component instead.

@flyingcircle even though there is an NPM package for the dropdown menu, are you still looking to implement it using RNE? IF yes, can I be assigned to it?

**Comment by venishpatidar** [comment]
@HariAcidReign I am already half way on it, Just matter of fact I was busy last few days so it had taken so long. Try solving open issues.

**Pull request closed without merging**
