### PR TITLE
added new component Dropdown

### PR DESCRIPTION
**Pull request by venishpatidar**
**What kind of change does this PR introduce?**
This PR will introduces a new component Dropdown to RNE.

**Did you add tests for your changes?**
Yes all changes are tested.

**If relevant, did you update the documentation?**
Yes Documents have been updated

**Summary**
There will be new component to Dropdown to RNE which was long awaited request, and need not to be installed from other npm packages separately. Also this dropdown can be act as Accordion  [https://media.geeksforgeeks.org/wp-content/uploads/20190522140003/accordian.gif](url) 

**Does this PR introduce a breaking change?**
No

dropdown

### CODE REVIEW

**Comment by venishpatidar** [comment]
@flyingcircle, upgraded it.

**Comment by flyingcircle** [comment]
Very nice! Yes, this is more like what I was thinking. I'm wondering though, it looks like you copied a good chunk of the code over. Why just use `ListItem` as is? Is there a compelling reason that We need `DropdownItem` and the associated components? Couldn't people just use `ListItem`?

**Comment by arpitBhalla** [comment]
I have a doubt, it is not called `dropdown`,  It can be Expandable or Accordion

**Comment by venishpatidar** [comment]
@flyingcircle yes, there is a reason, I was thinking as it would add more flexibility and rigidity. As further updated or modification to `ListItem` would not cause any bugs in dropdown. Also other way it would be more flexible to be change anything in particular.

**Comment by venishpatidar** [comment]
@arpitBhalla `Expandable` is great suggestion.

**Comment by venishpatidar** [comment]
@flyingcircle what's your opinion on should it need to be changed to `Expandable` or not.

**Comment by flyingcircle** [comment]
Decided to go with #2953 as it fit in a bit more with existing code.

**Pull request closed without merging**
