### PR TITLE
 #1717 react-native-training#1717 Added dividerWithMargin feature 

### PR DESCRIPTION
**Pull request by Prateek93a**
As per mentioned in the issue #1717, I added the feature for implementing borderBottom with nothing below the leftAvatars. I hope this would help

### CODE REVIEW

**Comment by Prateek93a** [comment]
Sorry for making so many PRs, but finally things worked out.
This dividerWithMargin feature will provider the border asked without using sectionlist.
It took a great deal of time to get it accepted by travis ci.
Hope this feature helps

**Comment by iRoachie** [comment]
Thanks for making at attempt at this feature. However, this isn't as simple as you think. The ListItem would need to make much more significant changes to be able to support this properly.

See case with ListItem where the avatar size is large:

```jsx
<ListItem
  leftAvatar={{ source: { uri }, size: 'large' }}
  title="Nah girl"
  dividerWithMargin
/>
```

Simulator Screen Shot - iPhone 7 - 2019-08-14 at 21 24 45

**Comment by Prateek93a** [comment]
I see, so this divider feature should cater to all the icon sizes and have different margins accordingly.
I will make the necessary changes.

**Comment by Prateek93a** [comment]
Finally pulled it off!!
Finally got through Travis ci. Now I have implemented dividerWithMarginLeft and dividerWithMarginRight, to handle both left and right avatars of all the sizes small, medium, large and xlarge with default value corresponding to small. I hope this time it works for all test cases.

**Comment by flyingcircle** [comment]
there has been recognition lately that we want to limit the number of props added to components, and this seems like it would contribute to "prop bloat". If there's another way to implement this without adding these props, you can open up a new PR

**Pull request closed without merging**
