### PR TITLE
Update Badge.js

### LINKED ISSUE #2212: Badge component should expose textProps
**Is your feature request related to a problem? Please Describe.**
When font scaling is enabled in a device there's no way to apply `allowFontScaling` property to `Badge` component.

**Describe the solution you'd like**
Exposing `textProps` (of the `Text` component) would allow setting this prop (`allowFontScaling`) to `false` in turn resolving the problem.

**Describe alternatives you've considered**
I can apply `allowFontScaling` to static `defaultProps` of react-native `Text` component, but it doesn't play nice with TypeScript and latest React.

### PR DESCRIPTION
**Pull request by FDiskas**
Closes #2212

### CODE REVIEW

**Comment by FDiskas** [comment]
Missing type definition updates - but... it's not my business :)

**Comment by FDiskas** [comment]
would be nice any comments :D :cop:

**Comment by flyingcircle** [comment]
1. It doesn't correctly solve the issue it claims to fix
2. You made a whole other series of changes that are outside of the original scope of the PR. I agree that the project needs to transition to typescript, but it should be in its own PR.

**Comment by FDiskas** [comment]
So i need just to change title of this pull request?

**Comment by flyingcircle** [comment]
And fix your changes, and likely update your PR to be current.

**Pull request closed without merging**
