### PR TITLE
Added a new Switch Components

### PR DESCRIPTION
**Pull request by hetanthakkar1**
The changes in withTheme.tsx are irrelavent. Those are just the changes that I did because I didn't execute git pull after cloning the repo.

Please review this component. Once approved I will create the docs for this component for issue #2873

### CODE REVIEW

**Comment by khushal87** [comment]
I have already created a PR and issue for Switch component before.

**Comment by hetanthakkar1** [comment]
@khushal87  I didn't know. Yeah let them decide

**Comment by khushal87** [comment]
No worries @hetanthakkar1

**Comment by hetanthakkar1** [comment]
Actually i just see the issues section and then started working on it so i didnt noticed ur pr

**Comment by khushal87** [comment]
Yes in the issues, I asked the mentors about working on it. I went through your code. It too looks great. Let mentors take the appropriate decision. I don't have any issues. Keep contributing 🚀

**Comment by flyingcircle** [comment]
@hetanthakkar1 you have a number of open PR's that need fixes/changes. Can you fix those before moving onto another item? I think we'll move forward with @khushal87 's version of Switch.

**Pull request closed without merging**
