### PR TITLE
Add thumbView prop on Slider

### PR DESCRIPTION
**Pull request by devth**
This is a simple proposal on how to solve https://github.com/react-native-training/react-native-elements/issues/1394

If it looks good I'll continue with tests and docs.

### CODE REVIEW

**Comment by devth** [comment]
Hey @iRoachie, any thoughts?

**Comment by iRoachie** [comment]
@devth I couldn't manage to get this working. Did you test this?

Here's my code to test:
```jsx
<Slider
  value={this.state.value}
  onValueChange={value => this.setState({ value })}
  thumbView={
    <View style={{ height: 30, width: 30, backgroundColor: 'pink' }} />
  }
  thumbStyle={{ height: 60, width: 60 }}
/>
```

simulator screen shot - iphone 6 - 2018-09-23 at 13 03 47

**Comment by iRoachie** [comment]
yarn link? You're referring to [symlinks](https://docs.npmjs.com/cli/link)? Symlinks don't work with the metro bundler

**Comment by devth** [comment]
Yep. I'm discovering that...the hard way 😄 (I'm a bit of a RN noob, sorry).

**Pull request closed without merging**
