### PR TITLE
Release 4.0.0-beta.0

### PR DESCRIPTION
**Pull request by flyingcircle**
**What kind of change does this PR introduce?**

**Did you add tests for your changes?**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

### CODE REVIEW

**Comment by flyingcircle** [comment]
@arpitBhalla @khushal87   I'm testing out the expo app on the latest dist branch for this release. I'm seeing to major issues that I think will prevent me from doing a release: The tooltip buttons aren't working and the linearProgress page is throwing an error. If we can get these issues resolved, I'll do this release. If anyone else wants to look into fixes for these issues, it would be very much appreciated.

**Comment by khushal87** [comment]
@arpitBhalla Any idea why is this coming up?

**Comment by arpitBhalla** [comment]
Tooltip APIs were changed and the component is now uncontrolled (stateless), might break for some users.

**Comment by khushal87** [comment]
Simulator Screen Shot - iPhone 13 - 2021-12-18 at 11 19 31
When I go to LinearProgress Screen.

**Comment by khushal87** [comment]
@flyingcircle There are issues with the Dialog component on the web version. I think we should drop the support.

**Comment by flyingcircle** [comment]
`LinearProgress` issue has been resolved. Thanks @arpitBhalla. I'll need to do a bit more reading to remember what was changed in tooltip. It's been so long now.

**Comment by flyingcircle** [comment]
@khushal87 I'm trying to build the docs and I'm using `yarn docs:build 4.0.0` but I'm getting an error:
```
/Users/jeremy/repos/rn/react-native-elements/website/scripts/docgen/docgenParser.ts:95
    if (prop?.defaultValue?.value.includes('\r\n')) {
                                  ^
TypeError: _m.value.includes is not a function
    at propFilter (/Users/jeremy/repos/rn/react-native-elements/website/scripts/docgen/docgenParser.ts:95:35)
    at Parser.propFilter (/Users/jeremy/repos/rn/react-native-elements/website/node_modules/react-docgen-typescript/src/buildFilter.ts:21:20)
    at Parser.getComponentInfo (/Users/jeremy/repos/rn/react-native-elements/website/node_modules/react-docgen-typescript/src/parser.ts:372:19)
    at /Users/jeremy/repos/rn/react-native-elements/website/node_modules/react-docgen-typescript/src/parser.ts:1403:28
    at Array.forEach (<anonymous>)
    at /Users/jeremy/repos/rn/react-native-elements/website/node_modules/react-docgen-typescript/src/parser.ts:1402:18
    at Array.reduce (<anonymous>)
    at parseWithProgramProvider (/Users/jeremy/repos/rn/react-native-elements/website/node_modules/react-docgen-typescript/src/parser.ts:1391:6)
    at Object.parse (/Users/jeremy/repos/rn/react-native-elements/website/node_modules/react-docgen-typescript/src/parser.ts:183:14)
    at Object.generateComponentDocs (/Users/jeremy/repos/rn/react-native-elements/website/scripts/docgen/generateComponentDocs.ts:8:6)
error Command failed with exit code 1.
```

Do you see the same thing?

**Comment by khushal87** [comment]
I just tested it, the problem is introduced after the tooltip PR you merged.

**Comment by khushal87** [comment]
```
Component = onPress || onLongPress || onPressIn || onPressOut
    ? Pressable
    : View,
```
@arpitBhalla Can you please simplify this logic? It seems like a code smell to me and it's the reason why the docs:build command is breaking. @flyingcircle I don't think this line is readable/understandable.

**Comment by khushal87** [comment]
So the root cause of the `docs:build` fail issue is the introduction of Pressable changes and those changes are not dealt with in the auto-completion of docs. I mentioned earlier to @arpitBhalla to fix them once he is done with the Pressable thing but I think he missed it.

**Comment by arpitBhalla** [comment]
> @arpitBhalla Can you please simplify this logic?

If any of these handlers present then container is Pressable else View 

> I mentioned earlier to @arpitBhalla to fix them

Please feel free to update them :slightly_smiling_face:

**Comment by flyingcircle** [comment]
Alright last piece before I publish. The docs CI build isn't working. Once we have that piece solved, then I'll publish the new version.

**Comment by arpitBhalla** [comment]
Need to re-trigger docs build CI

**Comment by flyingcircle** [comment]
@arpitBhalla  I re attempted it, same error

**Comment by arpitBhalla** [comment]
@flyingcircle Can we release beta first? there are few bugs in some new components.

**Comment by khushal87** [comment]
@flyingcircle I agree with @arpitBhalla on this.

**Pull request merged**
