### PR TITLE
MultiAvatar

### PR DESCRIPTION
**Pull request by dev-dano**
Hey @iRoachie, I accidentally closed the original PR. Here is the revised one.

**Usage**
```js
<MultiAvatar
  rounded
  size='large'
  separatorColor="yellow"
  separatorWidth={2}
  onPress={...}
  showEditButton={...}>

  <Avatar ... />
  <Avatar ... />
  ...

  OR

  { data.map((item, i) => <Avatar ... />) }
</MultiAvatar>
```

### CODE REVIEW

**Comment by iRoachie** [comment]
Hey @dev-dano since this is a new component, We'll need to do some additional things.
* Docs
* Typescript definitions

Let me know if you need help with any of them.

**Comment by dev-dano** [comment]
Hey @iRoachie, I am working on the doc. For the typescript definition, do I have to edit index.d.ts?

**Comment by iRoachie** [comment]
Yep index.d.ts is the file to edit

**Comment by iRoachie** [comment]
Hey @dev-dano do you mind resolving these conflicts so we can merge this in?

**Comment by dev-dano** [comment]
@iRoachie Thanks for reaching out, and sorry I should've let you know earlier, been very busy with work. I'll resolve the issue. Is there anything else you need?

**Comment by iRoachie** [comment]
Hey that’s okay! It’s just the conflicts that need to be resolved. But do it at your own time, no pressure

**Comment by dev-dano** [comment]
Hey @iRoachie, the conflict is resolved! Could you please help me with the testing? It works well on iOS. Here is an example:

```js
const data = [
  { name: '...', uri: '...' },
  { name: '...', uri: '...' },
];

<MultiAvatar
  size='large'
  separatorColor='yellow'
  separatorWidth={1}
  onPress={ ... }
  showPlaceholder={false} //this prop shows one placeholder for all images (fades out when all images are loaded).
>
  {data.map(elem => <Avatar title={elem.name} source={{ uri: elem.uri }} />)}
</MultiAvatar>
```

**Comment by flyingcircle** [comment]
I don't know how much work this would be to fix up this PR, but would @dev-dano be up for updating this PR to work with RNE 2? We could maybe add it to a RNE 2.1?

**Comment by flyingcircle** [comment]
I'm wondering if it might be easier to instead do something like a `MultiImage` instead that can then be used inside different components.

**Comment by flyingcircle** [comment]
Closing due to lack of activity

**Pull request closed without merging**
