### PR TITLE
[Fix, Improve] Dialog component

### PR DESCRIPTION
**Pull request by khushal87**
**What kind of change does this PR introduce?**
This PR improves the implementation of the Dialog component.

**Did you add tests for your changes?**
Yes
**If relevant, did you update the documentation?**

**Summary**
Improved:

- [x] Adapt to new patterns of the component.
- [x] Fix all usage of `any` as a type.
- [x] Improved the structure of the components.
- [x] Fix all the tsc issues related to the Dialog component.

**Does this PR introduce a breaking change?**
Yes, it improves the usage and implementation of the Dialog component.

**Other information**
Not required.

### CODE REVIEW

**Comment by arpitBhalla** [comment]
could you change the title of PR to `[Dialog] Fixed & Improved`, lets follow a pattern as in Material UI, ` [Component] Imperative commit message`

**Comment by khushal87** [comment]
@flyingcircle please review.

**Comment by flyingcircle** [comment]
This is throwing typescript errors in the demo app.

**Comment by khushal87** [comment]
This is strange. The dialog component has a lot of errors coming up, I am checking, we also have:
Screenshot_1623130427
and it is also not working on web currently.

**Comment by khushal87** [comment]
@flyingcircle fixed. Please review.

**Pull request merged**
