### PR TITLE
Fix input style

### LINKED ISSUE #2537: Default Input style changed 2.3.0 -> 2.3.1
**Explain what you did (Required)**

Updated from 2.3.0 to 2.3.1

**Expected behavior (Required)**

Same default styling as in v2.3.0

**Describe the bug (Required)**

Default styling for the Input Component has changed going from 2.3.0 to 2.3.1

**To Reproduce (Required)**

We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behaviour:

```bash
<Input
      ref={ref}
      editable={editable}
      inputContainerStyle={{
           borderBottomColor: 'transparent',
      }}
/>
```

**Screenshots (Required)**
v2.3.0
grafik

v2.3.1 (FontSize seems to be smaller, its very clear on a device)
grafik

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |  2.3.1  |
| react-native          |  0.63.2  |

### PR DESCRIPTION
**Pull request by JB1905**
Fixes #2537

### CODE REVIEW

**Comment by flyingcircle** [comment]
There is already an `inputStyle` for overriding the default styling.

**Comment by JB1905** [comment]
This is probably a fix for #2544

**Comment by alexttyip** [comment]
@flyingcircle @JB1905 This is indeed a direct fix for #2544.

**Comment by flyingcircle** [comment]
That makes more sense! thanks

**Pull request merged**
