### PR TITLE
Converted Slider to functional component

### PR DESCRIPTION
**Pull request by hetanthakkar1**
**Did you add tests for your changes?**

No. That's the only thing left. This functional component is fully functioning and can be tested manually, i just need to write the tests for it now

### CODE REVIEW

**Comment by flyingcircle** [comment]
Whew! This is quite the conversion! Looking forward to testing it out after you have the unit tests written.

**Comment by hetanthakkar1** [comment]
Yeah I'm on it

**Comment by hetanthakkar1** [comment]
@flyingcircle Do i need to construct the test written for class component in functional component or i can remove those and add some different tests!? because i feel converting those written already to functional is a bit hard and I'm learning how to do that

**Comment by flyingcircle** [comment]
`slider` is a bit different of a component. And writing tests for hooks is a pretty different task. Yeah, if you need to rewrite the tests, that's fine. Also make sure to pull in the latest `next` code. I fixed the other tests so that they pass in our CI.

**Comment by hetanthakkar1** [comment]
@flyingcircle So i will write my own tests removing those which i find difficult to convert to functional component tests. Will that be okay right!?

**Comment by hetanthakkar1** [comment]
I have made few mistakes while committing .

**Pull request closed without merging**
