### PR TITLE
Doc- fixed typos across files

### PR DESCRIPTION
**Pull request by Biki-das**
Fixed a few typos across the files.

### CODE REVIEW

**Comment by Biki-das** [comment]
@arpitBhalla , thanks for the merge, how do i run the project locally could you guide me , the `conributing.md` and `setup.md` talks about installing the dependencies and test , how do i run it on localhost, any help is appreciated.

**Comment by Biki-das** [comment]
> Follow this guide
> 
> https://reactnativeelements.com/docs/next/repo/contributing#setup

thanks a lot.

**Comment by Biki-das** [comment]
@arpitBhalla i am still not getting the thing i am looking for , this  helps to build expo stuff and all,and building files, i am looking towards running the website locally on my browser

**Comment by arpitBhalla** [comment]
try `yarn docs:serve`

**Comment by Biki-das** [comment]
> try `yarn docs:serve`

@arpitBhalla thanks , i am getting an error of `docusaurus` is not recognized as an internal or external command

**Comment by Biki-das** [comment]
Thanks @arpitBhalla , i think the setup docs some modifications regarding running the project locally on browsee!

**Comment by My-Name-Is-Nabil** [comment]
`Definations` is not a correct way to spell `Definitions`.

**Pull request merged**
