### PR TITLE
Removed ts-ignore tags

### PR DESCRIPTION
**Pull request by hetanthakkar1**
Removed ts-ignore from Image, AirbnbRating, Rating, Input, Searchbar, Tooltip.

### CODE REVIEW

**Comment by hetanthakkar1** [comment]
oops! I pushed the fetched changes by mistake. Please ignore those commits. This happened because i accidentally pushed before committing. Will take care next time. Please review @flyingcircle

**Review by arpitBhalla — COMMENTED** [review]
See this https://github.com/react-native-elements/react-native-elements/pull/2881#discussion_r597857387

**Comment by hetanthakkar1** [comment]
@arpitBhalla sorry i didn't got you!

**Comment by arpitBhalla** [comment]
We don't have to add `theme` here it's added in `withTheme`

**Comment by hetanthakkar1** [comment]
I think we do need to add them

**Comment by hetanthakkar1** [comment]
i think the problem lies in type checking of parameters  in withTheme function
`  WrappedComponent: React.ComponentType<P & ThemeProps<T>>,
`
Assigning value to parameters is the first line of the function and that's where problem arises so i think we need to add theme, updateThme and reaplaceThme

**Comment by arpitBhalla** [comment]
@hetanthakkar1 only class components have this problem...

**Comment by hetanthakkar1** [comment]
> @arpitBhalla I think the problem lies in type checking of parameters in withTheme function
> ` WrappedComponent: React.ComponentType<P & ThemeProps<T>>,`
> Assigning value to parameters is the first line of the function and that's where problem arises so i think we need to add theme, updateThme and reaplaceThme

@arpitBhalla  yeah! did you get this!? why we need to include in class components!?

**Comment by flyingcircle** [comment]
@arpitBhalla is correct. I do not want these types individually added to every component. A better solution is needed.

**Pull request closed without merging**
