### PR TITLE
Add new Counter component

### PR DESCRIPTION
**Pull request by khushal87**
**What kind of change does this PR introduce?**
This introduces a counter component.

**Did you add tests for your changes?**
Yes
**If relevant, did you update the documentation?**
I will add the documentation soon
**Summary**

- [x] Code
- [x] Tests
- [ ] Docs

**Does this PR introduce a breaking change?**
Yes, this introduces a new Counter component using the components from the package.

**Other information**
NA

Reference issue - #counter

### CODE REVIEW

**Comment by pranshuchittora** [comment]
Why?
Any context or discussion I am missing?

**Comment by khushal87** [comment]
> Why?
> Any context or discussion I am missing?
> 
> Ref: https://reactnativetraining.slack.com/archives/C01R24E3YPK/p1616114618044100?thread_ts=1616078643.040500&cid=C01R24E3YPK

Hello sir I have raised a issue before #2904 @pranshuchittora

**Comment by pranshuchittora** [comment]
As I can see, there are no comments from the community or the maintainers.

**Comment by khushal87** [comment]
@pranshuchittora Yes, I didn't receive a comment yet, maybe it was somehow missed. I raised it 4 days ago and didn't receive a reply, I didn't have a yes or a nor, so I worked on it as I found this may help the community and users. If you find it not useful I may close the PR and the issue.

**Pull request closed without merging**
