### PR TITLE
RNE as Monorepo

### PR DESCRIPTION
**Pull request by arpitBhalla**
includes website, base package and demoApp [Linked]

### CODE REVIEW

**Comment by flyingcircle** [comment]
Gotta fix the merges for this ticket.

**Comment by arpitBhalla** [comment]
@flyingcircle Please review

**Comment by flyingcircle** [comment]
I'm hitting this error when trying to bring up the example app:
```
Could not resolve "@expo/vector-icons/Icon" in file /Users/jeremy/repos/rn/react-native-elements/packages/base/src/Icon/Icon.tsx.
```

**Comment by arpitBhalla** [comment]
I think there is some issue with metro bundler, I tried publishing demo app, the final bundle is over 4mb in size.

**Pull request merged**
