### PR TITLE
[Text] 💥 Reduce Props <OnHold>

### PR DESCRIPTION
**Pull request by arpitBhalla**
Similar to https://material-ui.com/components/typography/
`variant` will replace `h1 h2 h3 h4 caption` props

```javascript
<Text variant="h1" style={{}} />
```

### CODE REVIEW

**Comment by arpitBhalla** [comment]
@pranshuchittora @flyingcircle Kindly Review

**Comment by arpitBhalla** [comment]
@pranshuchittora @flyingcircle Need approval for Further work

**Comment by arpitBhalla** [comment]
@pranshuchittora @flyingcircle, Need approval to work further on this.

**Comment by khushal87** [comment]
Please resolve merge conflicts.

**Pull request closed without merging**
