### PR TITLE
Listitem type

### LINKED ISSUE #2460: [Suggestion] ListItem -> Add Android ripple effect
**Is your feature request related to a problem? Please Describe.**
Currently, the ListItem uses TouchableHighlight component. It doesn't alllow the Android ripple effect on pressIn. It really should use the new [Pressable](https://reactnative.dev/docs/pressable) (maybe not good yet, as it requires Native v0.63) or [TouchableNativeFeedback](https://reactnative.dev/docs/touchablenativefeedback) ([How to make TouchableNative fallback to TouchableHighlight](https://stackoverflow.com/a/40060442/10247962))

### PR DESCRIPTION
**Pull request by flyingcircle**
Fixes #2460

### CODE REVIEW

**Comment by flyingcircle** [comment]
@SrBrahma please check this out and see if this fixes the typescript error that you were talking about.

**Comment by SrBrahma** [comment]
As it isn't in master, how can I test it? Maybe npm update [and what]?

**Comment by flyingcircle** [comment]
@SrBrahma You can always check out a github branch as such: `yarn add https://github.com/flyingcircle/react-native-elements#listitem-type`

**Comment by SrBrahma** [comment]
Yes, android_ripple is now passable without errors. However, to pass Pressable into Component prop, it still needs 'as any'. Not really a big problem like the android_ripple, as it required the `{...{ android_ripple: { yourProps } }}` hack that took me some time to find out.

Thanks!

**Comment by flyingcircle** [comment]
Awesome, I'll merge this soon and hopefully get a new official version out soon as well. The other ticket you opened for the enhancement may take a bit more updating to get working.

**Pull request merged**
