### PR TITLE
Add  RTL support to tooltip

### PR DESCRIPTION
**Pull request by BatDroid**
This PR fix the bug which was reported in issue #2125 .

### CODE REVIEW

**Comment by iRoachie** [comment]
I ended up with behaviour like this:
Screenshot_1572275864

**Comment by BatDroid** [comment]
> I ended up with behaviour like this:
> 
> Screenshot_1572275864

@iRoachie 
Oh, give me a couple of days (Im busy this week) to fix it. did you face it over a simple usage or passing specific props?

**Comment by iRoachie** [comment]
```jsx
<View style={styles.container}>
  <Tooltip popover={<Text>Info here</Text>}>
    <Icon name="info" />
  </Tooltip>
</View>


///
const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 15,
    paddingTop: Constants.statusBarHeight,
    justifyContent: 'center',
    alignItems: 'flex-start',
    backgroundColor: 'rgba(0,0,0,.2)',
  },
});

```

**Comment by BatDroid** [comment]
> ```js-jsx
> <View style={styles.container}>
>   <Tooltip popover={<Text>Info here</Text>}>
>     <Icon name="info" />
>   </Tooltip>
> </View>
> 
> 
> ///
> const styles = StyleSheet.create({
>   container: {
>     flex: 1,
>     padding: 15,
>     paddingTop: Constants.statusBarHeight,
>     justifyContent: 'center',
>     alignItems: 'flex-start',
>     backgroundColor: 'rgba(0,0,0,.2)',
>   },
> });
> ```

@iRoachie 
I'll look into it. thank you. I should have tested on android as well as Ios. sorry, my bad.

**Comment by flyingcircle** [comment]
Closing in favor of: #2319

**Pull request closed without merging**
