### PR TITLE
Image Component shoule accept onLoad prop

### PR DESCRIPTION
**Pull request by Qiyu8**
fix issue 2206

### CODE REVIEW

**Comment by TomJKlug** [comment]
For my own education. Won't this cause issues with the animation? Since you aren't running the onLoad that is provided with the RNE component? Should it not run the onLoad of the RNE and the onLoad passed?

**Comment by iRoachie** [comment]
Correct @TomJKlug, this PR fixes one problem and breaks the Image component.

**Comment by Qiyu8** [comment]
The purpose of RNE image is to ensure customized smooth image load transitioning, so the original onLayout、onLoad、onLoadStart and onLoadEnd function is abandoned. if someone wants to use these function, they should import image from react-native, is that correct?

**Comment by iRoachie** [comment]
They might want to keep the same animation behaviour but have custom logic on the `onLoad`.

**Comment by Qiyu8** [comment]
we can put the animation behaviour on **onLoadEnd**, which is not commonly used, while keep the important passed function **onLoad**, How about that?

**Comment by iRoachie** [comment]
Already fixed by https://github.com/react-native-elements/react-native-elements/commit/69ea8819e9666157f48e756e272ba0396ea52c83

**Pull request closed without merging**
