### PR TITLE
Fixed issue of Cannot read property 'grey' of undefined in ListItem

### PR DESCRIPTION
**Pull request by imakshar**
ListItem on a web throwing error `cannot read property  grey of undefined`

issue : `color: Platform.select(theme.colors.platform).grey;`

**theme.colors.platform :**
 
themePlatformObject

`theme.colors.platform` is a react-native theme object it' doesn't contain a `web` platform, to make it work on the `web` as well we have to check explicitly `web` platform. 

it will be fixed by checking the web platform explicitly,
```js let greyColor =
    Platform.OS === 'web' // select grey color on web 
      ? theme.colors.grey0 || '#7d7d7d'
      : Platform.select(theme.colors.platform).grey;

### CODE REVIEW

**Comment by flyingcircle** [comment]
I would say that this is not the correct to fix this. Instead a default needs to be added to the base theme in `colors.js`

**Comment by imakshar** [comment]
Oh, I see. I didn't checkout the `colors.js` 
can I add `web` platform to `colors.js` ? on Which basis I need to assign colors ? or should I follow same color properties as android or ios. @flyingcircle

**Comment by flyingcircle** [comment]
yeah, as far as I know that grey would be the only one actually used by default. There's also a doc on theming that would updated as well.

**Comment by imakshar** [comment]
Thanks, @flyingcircle for your valuable feedback.  
I hope, it's ready to merge. or if it's already fixed feel free to close PR.

**Comment by flyingcircle** [comment]
@imakshar cna you also edit the `website/docs/customization.md` file so that it mentions this as well?

**Comment by imakshar** [comment]
@flyingcircle ya, sure. let me update it too.

**Comment by imakshar** [comment]
@flyingcircle 
changes added to `website/docs/customization.md`  as well.

**Comment by pranshuchittora** [comment]
Build failing due to improper linting and old snapshots.
No worries, raising a fix ASAP.

**Comment by LinusU** [comment]
Is there any plans to cut a release with this fix in it? This is currently causing a crash in our app... 😅 

ping @flyingcircle

**Comment by Aparus** [comment]
@LinusU , thank you, you helped me )
Should I remove this code after RNE update? 

> edit: for anyone else needing a quick fix:
> 
> ```ts
> import { colors } from 'react-native-elements'
> 
> // FIXME: https://github.com/react-native-elements/react-native-elements/pull/2561
> 
> // @ts-ignore The typings are also missing "web"
> if (colors.platform.web == null) {
>   // @ts-ignore The typings are also missing "web"
>   colors.platform.web = {
>     primary: '#2089dc',
>     secondary: '#ca71eb',
>     grey: '#393e42',
>     searchBg: '#303337',
>     success: '#52c41a',
>     error: '#ff190c',
>     warning: '#faad14'
>   }
> }
> ```

**Comment by LinusU** [comment]
> Should I remove this code after RNE update?

Yes ☺️ 

As soon as this PR is released and you upgrade to that version, you can safely remove the workaround.

**Comment by fabdarice** [comment]
Hey, I am still seeing this error for ListItem even with the latest release?

**Comment by flyingcircle** [comment]
@imakshar contact me on Slack for a small thank you token for this PR.

**Pull request merged**
