### PR TITLE
Modified the props of Icon color to incorporate PlatFormColor for issue  #2794

### PR DESCRIPTION
**Pull request by hetanthakkar1**
I am a bit skeptical about my approach as I have changed the type of color prop to any.  I tried using the type `color: string | object` but that resulted in the ts error saying that **object is not assignable to string**. 

One thing I am sure of is that we need to incorporate the object as one of the types for color prop as the PlatformColor returns an object. So I thought that otherwise also we are passing object and string so assigning type any to color prop might make sense

Secondly, the TouchableNativeFeedback ripple effect takes a color as an argument whose type must be a string. Changeing that to include the object  type will require a modification in the core package so when the color is passed as PlatformColor( which is an object) we won't be able to pass that into TouchableNativeFeedback ripple effect so as a default I passed  `theme.color.black `(we can change this to any color)

### CODE REVIEW

**Comment by hetanthakkar1** [comment]
@flyingcircle  what are your thoughts about my approach

**Comment by flyingcircle** [comment]
I can appreciate the attempt and I thought of `any` myself when trying to come up with a solution to it. There's a deeper problem here though that I think will require a better solution. Perhaps it might be worth it to do some investigation into the types from `vector-icons` and `colors` as it seems like there's something between those 2 that isn't working correctly. My hunch here is actually that the `vector-icons` types library might have a bug in it?

**Comment by hetanthakkar1** [comment]
I'm investigating the issue. If we couldn't find the issue causing that type problem,can we then implement my solution as the last resort!?

**Comment by flyingcircle** [comment]
Solved by https://github.com/react-native-elements/react-native-elements/pull/2847

**Pull request closed without merging**
