### PR TITLE
Fix SearchBar placeholder tsc issue

### PR DESCRIPTION
**Pull request by khushal87**
**What kind of change does this PR introduce?**
It **fixes the Searchbar Tsc warning for placeholder**

**Did you add tests for your changes?**
Not required, but the code is tested well locally
**If relevant, did you update the documentation?**
Not needed
**Summary**
error_placeholder
solved_placeholder

**Does this PR introduce a breaking change?**
No.

**Other information**
Reference issue - https://github.com/react-native-elements/react-native-elements/issues/2870

Looking forward for suggestions and review.

### CODE REVIEW

**Comment by flyingcircle** [comment]
This doesn't make sense. `placeholder` is already inherited through `TextInputProps`

**Comment by khushal87** [comment]
But it still gives a tsc issue. Let me find a fix for it then. @flyingcircle

**Comment by flyingcircle** [comment]
No, I'm against patchwork fixes like this. There is some reason why these types aren't lining up correctly, but adding `placeholder` to SearchBar just hides the issue in a harder to find way.

**Comment by khushal87** [comment]
Okay, I will work and look at some other fixes.

**Pull request closed without merging**
