### PR TITLE
feat: Added containerStyle and tabItemContainerStyle to TabView component

### PR DESCRIPTION
**Pull request by hoshomoh**
**What kind of change does this PR introduce?**

- Updated patch with master
- feat: Added containerStyle and tabItemContainerStyle to TabView component
- fix: Updated TabView component to use React Native `useWindowDimensions` because the width and height is updated when orientation changes
- Updated the docs to reflect newly added props for the TabView component

**Did you add tests for your changes?**

No

**If relevant, did you update the documentation?**

Yes

**Summary**

I have been using [react-native-elements](https://github.com/react-native-elements/react-native-elements) across multiple projects for a while now. I recently noticed that it is impossible to add custom style to the TabView and TabView.Item containers.  And also the container `width` was using React Native `Dimension` which doesn't update the `width` when the user changes orientation.

**Does this PR introduce a breaking change?**

Not needed

**Other information**

### CODE REVIEW

**Comment by hoshomoh** [comment]
My changes are in commit https://github.com/hoshomoh/react-native-elements/commit/8943247b5910e1eaa0f0f7ce7f684763f551c6ba. I updated `patch` with master is why you see the many changes.

**Review by khushal87 — COMMENTED** [review]
Why is this PR against the `patch` branch? Can you go through the contributing guidelines and update the PR as per that. The new changes should always be against the `next` branch.

**Comment by hoshomoh** [comment]
> Why is this PR against the `patch` branch? Can you go through the contributing guidelines and update the PR as per that. The new changes should always be against the `next` branch.

I made my changes against the next branch. I might have made a mistake when opening the PR. Just switched to next

**Comment by hoshomoh** [comment]
@khushal87 actually now I remember why I did this. I wasn't sure what the release cycle for next was, so I also branched out from the patch branch and made the fixes there also. Which Is why you have this PR. You can close and review the next version https://github.com/react-native-elements/react-native-elements/pull/3191

**Comment by flyingcircle** [comment]
Yeah, the patch branch really hasn't been used or updated in a long time. Maybe you can rework a PR to be tested against the `next` branch?

**Comment by hoshomoh** [comment]
> Yeah, the patch branch really hasn't been used or updated in a long time. Maybe you can rework a PR to be tested against the `next` branch?

This PR was branched out of master https://github.com/react-native-elements/react-native-elements/pull/3191

**Comment by flyingcircle** [comment]
@hoshomoh yeah sorry about the confusion. Master branch is very far out of date. In the developer documentation it does say that all work should be done off of the `next` branch.

**Comment by hoshomoh** [comment]
> @hoshomoh yeah sorry about the confusion. Master branch is very far out of date. In the developer documentation it does say that all work should be done off of the `next` branch.

Sorry I meant the next branch 🙈

**Pull request closed without merging**
