### PR TITLE
update BottomSheet so that it isn't bound by a max height

### PR DESCRIPTION
**Pull request by flyingcircle**
Fixes: #2726

@guilhermedess can you try this out and see if everything works as expected?

### CODE REVIEW

**Review by guilhermedess — APPROVED** [review]
image

It worked!!!!!!
This is evidence.

I'm new to the open source community, how and when do you implement this change?
Sorry for my ignorance

**Comment by guilhermedess** [comment]
> Fixes: #2726
> 
> @guilhermedess can you try this out and see if everything works as expected?



> image
> 
> It worked!!!!!!
> This is evidence.
> 
> I'm new to the open source community, how and when do you implement this change?
> Sorry for my ignorance

**Comment by flyingcircle** [comment]
I'd like to get as many changes as possible into a release, but I'll aim to have it released by early January.

**Comment by guilhermedess** [comment]
thank you so much
it was a very good experience for me
had never done anything like that

55 (11) 94175-2026
Guilherme Silveira

________________________________
De: flyingcircle <notifications@github.com>
Enviado: quarta-feira, 23 de dezembro de 2020 20:50
Para: react-native-elements/react-native-elements <react-native-elements@noreply.github.com>
Cc: Guilherme de Souza Silveira <guilherme.souzaaa@live.com>; Mention <mention@noreply.github.com>
Assunto: Re: [react-native-elements/react-native-elements] update BottomSheet so that it isn't bound by a max height (#2727)


I'd like to get as many changes as possible into a release, but I'll aim to have it released by early January.

**Pull request merged**
