### PR TITLE
[Fix] Icon raised prop style shadow issue

### LINKED ISSUE #3058: Icon raised border problem on iOS
**Explain what you did (Required)**
Border of Icon raised on iOS is not visible

**Expected behavior (Required)**
Expecting to work as android

**Describe the bug (Required)**
Border of Icon is not visible anymore

**To Reproduce (Required)**
https://snack.expo.io/yYA7fKAV5

**Screenshots (Required)**
iOS:
Screenshot 2021-05-28 at 10 44 25

Android:
Screenshot 2021-05-28 at 10 50 35

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements | 3.4.1        |
| react-native          |  0.64.1       |

### PR DESCRIPTION
**Pull request by khushal87**
This PR uses the value as https://ethercreative.github.io/react-native-shadow-generator/ for elevation 2 which will create almost the same effect on both android and iOS devices.

### CODE REVIEW

**Comment by flyingcircle** [comment]
This did not work likely related to `overflow: 'hidden'` see: https://stackoverflow.com/questions/44908580/react-native-shadow-not-appearing 

I tested in demo app iOS 14.5. Please test before submitting a PR.

**Comment by khushal87** [comment]
I used this https://ethercreative.github.io/react-native-shadow-generator/ to make the values uniform, and I tested on the snack.

**Comment by flyingcircle** [comment]
Can you share the snack that shows this working?

**Comment by khushal87** [comment]
https://github.com/react-native-elements/react-native-elements/issues/3058#issuecomment-851011250 this is the screenshot. While I tested, I just did this to make the values uniform, not sure if this is solved.

**Comment by notjulian** [comment]
hi @flyingcircle,
please take a look at this working
https://snack.expo.io/GWTAqO-W2

and this one not working
https://snack.expo.io/41_NPoKAc

thanks so much for this toolkit

**Pull request closed without merging**
